# frozen_string_literal: true

require_relative "lib/fillers_remover/version"

Gem::Specification.new do |spec|
  spec.name          = "fillers_remover"
  spec.version       = FillersRemover::VERSION
  spec.authors       = ["yasaichi"]
  spec.email         = ["yasaichi@users.noreply.github.com"]

  spec.summary       = "Remove fillers using Transcript generated by Amazon Transcribe"
  spec.description   = "FillerRemover automatically removes fillers from your audio"\
                       "using Transcript generated by Amazon Transcribe"
  spec.homepage      = "https://github.com/yasaichi/fillers_remover"
  spec.license       = "MIT"
  spec.required_ruby_version = Gem::Requirement.new(">= 3.0.0")

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/yasaichi/fillers_remover"
  spec.metadata["changelog_uri"] = "https://github.com/yasaichi/fillers_remover/blob/main/CHANGELOG.md"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{\A(?:test|spec|features)/}) }
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency "thor", "~> 1.0"
  spec.add_dependency "wav-file", "~> 0.0.3"

  # For more information and examples about making a new gem, checkout our
  # guide at: https://bundler.io/guides/creating_gem.html
end
